// src/styles/index.ts
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f0f23',
  },
  header: {
    backgroundColor: '#1a1a2e',
    paddingTop: 50, // 增加顶部padding适应透明状态栏
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  headerButton: {
    padding: 8,
  },
  headerButtonText: {
    fontSize: 20,
  },
  currentSessionCard: {
    backgroundColor: '#16213e',
    margin: 15,
    padding: 20,
    borderRadius: 15,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  focusMode: {
    backgroundColor: '#667eea',
    padding: 30,
    margin: 15,
  },
  sessionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  sessionIcon: {
    fontSize: 32,
    marginRight: 20,
  },
  sessionInfo: {
    flex: 1,
  },
  sessionName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 8,
  },
  sessionTime: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#4A90E2',
    marginBottom: 5,
  },
  sessionElapsed: {
    fontSize: 14,
    color: '#888',
  },
  pauseButton: {
    backgroundColor: '#FF9800',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pauseButtonText: {
    fontSize: 20,
  },
  resumeButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resumeButtonText: {
    fontSize: 20,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  progressTrack: {
    flex: 1,
    height: 8,
    backgroundColor: '#333',
    borderRadius: 4,
    marginRight: 10,
  },
  progressFill: {
    height: '100%',
    borderRadius: 4,
  },
  progressText: {
    color: '#888',
    fontSize: 12,
    fontWeight: '600',
    minWidth: 35,
  },
  scrollView: {
    flex: 1,
    padding: 15,
  },
  majorBlocksContainer: {
    marginBottom: 20,
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
  },
  majorBlockCard: {
    backgroundColor: '#16213e',
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    borderLeftWidth: 4,
  },
  majorBlockHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  majorBlockName: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  majorBlockTime: {
    color: '#888',
    fontSize: 14,
  },
  blockSelector: {
    marginBottom: 15,
    maxHeight: 120,
  },
  blockSelectorItem: {
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 12,
    marginRight: 10,
    alignItems: 'center',
    minWidth: 100,
  },
  blockSelectorIcon: {
    fontSize: 20,
    marginBottom: 5,
  },
  blockSelectorName: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 2,
  },
  blockSelectorTime: {
    color: '#ffffff',
    fontSize: 10,
    opacity: 0.8,
  },
  tempLabel: {
    color: '#ffffff',
    fontSize: 8,
    backgroundColor: 'rgba(255,255,255,0.3)',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
    marginTop: 2,
  },
  addTempButton: {
    backgroundColor: '#FF5722',
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderRadius: 12,
    marginRight: 10,
    alignItems: 'center',
    minWidth: 80,
  },
  addTempButtonText: {
    fontSize: 20,
    marginBottom: 5,
  },
  addTempButtonLabel: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  parentBlock: {
    backgroundColor: '#16213e',
    borderRadius: 15,
    marginBottom: 15,
    overflow: 'hidden',
  },
  activeParentBlock: {
    borderWidth: 2,
    borderColor: '#4A90E2',
    elevation: 8,
  },
  collapsedParentBlock: {
    opacity: 0.7,
  },
  parentBlockHeader: {
    padding: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  parentBlockTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  parentIcon: {
    fontSize: 20,
    marginRight: 10,
  },
  parentName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    flex: 1,
  },
  collapseIndicator: {
    fontSize: 12,
    color: '#ffffff',
    marginLeft: 10,
    transform: [{ rotate: '0deg' }],
  },
  collapseIndicatorCollapsed: {
    transform: [{ rotate: '-90deg' }],
  },
  addChildButton: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  addChildButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  childrenContainer: {
    padding: 10,
  },
  childBlock: {
    backgroundColor: '#1a1a2e',
    borderRadius: 10,
    marginBottom: 8,
    borderLeftWidth: 4,
    position: 'relative',
  },
  activeChildBlock: {
    backgroundColor: '#2a3f5f',
    elevation: 4,
  },
  deleteButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    backgroundColor: '#D0021B',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  deleteButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  childContent: {
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  childIcon: {
    fontSize: 16,
    marginRight: 12,
  },
  childInfo: {
    flex: 1,
  },
  childName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 2,
  },
  childTime: {
    fontSize: 12,
    color: '#4A90E2',
    marginBottom: 1,
  },
  childUsed: {
    fontSize: 12,
    color: '#888',
    marginBottom: 1,
  },
  pauseInfo: {
    fontSize: 10,
    color: '#FF9800',
    marginBottom: 1,
  },
  tempIndicator: {
    fontSize: 8,
    color: '#FF5722',
    backgroundColor: 'rgba(255, 87, 34, 0.2)',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    alignSelf: 'flex-start',
  },
  activeIndicator: {
    backgroundColor: '#4CAF50',
    borderRadius: 15,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeIndicatorText: {
    fontSize: 14,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#0f0f23',
  },
  modalHeader: {
    backgroundColor: '#1a1a2e',
    paddingTop: 40,
    paddingBottom: 15,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    flex: 1,
  },
  modalSubtitle: {
    fontSize: 14,
    color: '#888',
    textAlign: 'center',
    marginBottom: 20,
  },
  closeButton: {
    fontSize: 24,
    color: '#ffffff',
    padding: 5,
  },
  templateList: {
    flex: 1,
    padding: 20,
  },
  templateCard: {
    backgroundColor: '#16213e',
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
  },
  templateName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
    marginBottom: 10,
  },
  templateDescription: {
    fontSize: 14,
    color: '#888',
    marginBottom: 5,
  },
  templateSubBlocks: {
    fontSize: 12,
    color: '#4A90E2',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#16213e',
    borderRadius: 20,
    padding: 25,
    width: width * 0.9,
    maxWidth: 400,
    maxHeight: height * 0.8,
  },
  destinationOption: {
    borderWidth: 2,
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
  },
  destinationName: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 5,
  },
  destinationInfo: {
    fontSize: 12,
    color: '#888',
  },
  destinationHint: {
    fontSize: 10,
    color: '#666',
    fontStyle: 'italic',
    marginTop: 2,
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  settingLabel: {
    color: '#ffffff',
    fontSize: 16,
    flex: 1,
  },
  settingButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  settingButton: {
    backgroundColor: '#333',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
  },
  settingButtonActive: {
    backgroundColor: '#4A90E2',
  },
  settingButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  inputLabel: {
    color: '#ffffff',
    fontSize: 14,
    marginBottom: 5,
    marginTop: 15,
  },
  textInput: {
    backgroundColor: '#1a1a2e',
    color: '#ffffff',
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
  },
  emojiContainer: {
    maxHeight: 50,
    marginTop: 5,
  },
  emojiOption: {
    padding: 8,
    marginRight: 5,
    borderRadius: 8,
    backgroundColor: '#1a1a2e',
  },
  selectedEmoji: {
    backgroundColor: '#4A90E2',
  },
  emojiText: {
    fontSize: 20,
  },
  colorContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 5,
  },
  colorOption: {
    width: 30,
    height: 30,
    borderRadius: 15,
    margin: 5,
  },
  selectedColor: {
    borderWidth: 3,
    borderColor: '#ffffff',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 25,
    gap: 10,
  },
  cancelButton: {
    backgroundColor: '#666',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
    flex: 1,
  },
  cancelButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '600',
  },
  saveButton: {
    backgroundColor: '#4A90E2',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
    flex: 1,
  },
  saveButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '600',
  },
  secondaryButton: {
    backgroundColor: '#667eea',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 10,
    flex: 1,
  },
  secondaryButtonText: {
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '600',
  },
  activityLogList: {
    flex: 1,
    padding: 15,
  },
  activityLogItem: {
    backgroundColor: '#16213e',
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  activityIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  activityIconText: {
    fontSize: 16,
  },
  activityInfo: {
    flex: 1,
  },
  activityDescription: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  activityTime: {
    color: '#888',
    fontSize: 12,
  },
  statsContainer: {
    padding: 20,
  },
  statItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  statLabel: {
    color: '#ffffff',
    fontSize: 16,
  },
  statValue: {
    color: '#4A90E2',
    fontSize: 16,
    fontWeight: '600',
  },
});